services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    restart: always
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
